title: Guilherme Carreiro
author: Guilherme Carreiro
email: karreiro@gmail.com
description: >
  Sou Guilherme Carreiro. Atualmente trabalho para Red Hat,
  100% do tempo com código Open Source.
  Sou membro do KIE Group e atuo principalmente no Drools e no jBPM,
  evoluindo os principais editores do Drools Workbench.
baseurl: ''
url: 'http://karreiro.com'
google_analytics: 'UA-108493780-1'
twitter_username: karreiro_
github_username:  karreiro
markdown: kramdown

disqus:
  shortname: karreiro

plugins:
  - jekyll-feed

talks:

  - title: 'JavaScript<br />The Right Way'
    conference: 'FLISOL Campinas'
    year: 2013
    color: '#FBAA18'
    file_name: '2013-javascript-the-right-way.pdf'

  - title: 'JavaScript de Qualidade: Hoje, Amanhã e Sempre'
    conference: 'DevCamp / TDC São Paulo'
    year: 2014
    color: '#387EA4'
    file_name: '2014-qualidade-js.pdf'

  - title: 'Metaprogramação<br />na prática'
    conference: 'TDC Florianópolis'
    year: 2015
    color: '#626A8A'
    file_name: '2015-tdc-metaprogramacao.pdf'

  - title: 'DSLs em Ruby'
    conference: 'TDC São Paulo'
    year: 2015
    color: '#CA6063'
    file_name: '2015-dsls-ruby.pdf'

  - title: 'Action Cable<br />em Ação'
    conference: 'TDC São Paulo / Rupy'
    year: 2016
    color: '#5E327C'
    file_name: '2016-actioncable.pdf'

  - title: '5 pilares para uma aplicação Java Web bem-sucedida'
    conference: 'Red Hat Forum / JUG Campinas'
    year: 2017
    color: '#A73636'
    file_name: '2017-5pilares.pdf'
